# escape=`

# Installer image
FROM mcr.microsoft.com/windows/servercore:ltsc2022 AS installer

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# Retrieve .NET Core Runtime
# USER ContainerAdministrator
RUN $dotnet_version = '8.0.11'; `
    Invoke-WebRequest -OutFile dotnet-installer.exe https://download.visualstudio.microsoft.com/download/pr/27bcdd70-ce64-4049-ba24-2b14f9267729/d4a435e55182ce5424a7204c2cf2b3ea/windowsdesktop-runtime-8.0.11-win-x64.exe; `
    ./dotnet-installer.exe /S

# Runtime image 
FROM mcr.microsoft.com/dotnet/aspnet:8.0.11-nanoserver-ltsc2022 as nano-with-dotnet

ENV `
    # Enable detection of running in a container
    DOTNET_RUNNING_IN_CONTAINER=true

# this dll is required 
COPY DWrite.dll /Windows/System32
COPY kernel32.dll /Windows/System32

# copy windows c++ redistributable 
# copy the content of 'C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Redist\MSVC\14.34.31931\onecore\x64\Microsoft.VC143.CRT'
# to the directory'vc_redist.x64' (the subfolder in the directory with Dockerfile on your PC)
COPY ["vc_redist.x64", "/Program Files/vc_redist.x64"]  

COPY --from=installer ["/Program Files/dotnet", "/Program Files/dotnet"]

# In order to set system PATH, ContainerAdministrator must be used
USER ContainerAdministrator
RUN setx /M PATH "%PATH%;C:\Program Files\dotnet;C:\Program Files\vc_redist.x64"
USER ContainerUser


