# escape=`

FROM mcr.microsoft.com/dotnet/runtime:8.0.19-windowsservercore-ltsc2025 as application-base

ENV `
    # Enable detection of running in a container
    DOTNET_RUNNING_IN_CONTAINER=true

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# Run PowerShell commands
RUN Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine -Force

RUN $dotnet_version = '8.0.19'; `
    Invoke-WebRequest -OutFile dotnet-installer.exe https://builds.dotnet.microsoft.com/dotnet/WindowsDesktop/8.0.19/windowsdesktop-runtime-8.0.19-win-x64.exe; `
    ./dotnet-installer.exe /S`
    Remove-Item -Force dotnet-installer.exe;

RUN Invoke-WebRequest "https://aka.ms/vs/17/release/vc_redist.x64.exe" -OutFile "vc_redist.x64.exe"; `
    Start-Process -filepath C:\vc_redist.x64.exe -ArgumentList "/install", "/passive", "/norestart" -Passthru | Wait-Process; `
    Remove-Item -Force vc_redist.x64.exe;