# escape=`

FROM mcr.microsoft.com/dotnet/aspnet:8.0.11-windowsservercore-ltsc2022 as application-base

ENV `
    # Enable detection of running in a container
    DOTNET_RUNNING_IN_CONTAINER=true

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# Run PowerShell commands
RUN Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine -Force

RUN $dotnet_version = '8.0.11'; `
    Invoke-WebRequest -OutFile dotnet-installer.exe https://download.visualstudio.microsoft.com/download/pr/27bcdd70-ce64-4049-ba24-2b14f9267729/d4a435e55182ce5424a7204c2cf2b3ea/windowsdesktop-runtime-8.0.11-win-x64.exe; `
    ./dotnet-installer.exe /S`
    Remove-Item -Force dotnet-installer.exe;

RUN Invoke-WebRequest "https://aka.ms/vs/17/release/vc_redist.x64.exe" -OutFile "vc_redist.x64.exe"; `
    Start-Process -filepath C:\vc_redist.x64.exe -ArgumentList "/install", "/passive", "/norestart" -Passthru | Wait-Process; `
    Remove-Item -Force vc_redist.x64.exe;